### PR TITLE
mavflightmode.js : make rover known type

### PR DESCRIPTION
**Pull request by nkruzan**
don't output a log message that its unsupported when its a rover

### CODE REVIEW

**Comment by davidbuzz** [comment]
mode_mapping_acm is defined at line 39, and is/was for ArduCopter, not necesarily ArduRover .  i i don't know much about Rover, does it use the same Mode name's as Copter..? This commit asssumes it does.

**Comment by nkruzan** [comment]
Thanks for taking the time to review. I added the rover mode list. It looks like there need to be more work in mode_mapping and mode_mapping_inv to allow other than plane also.

**Comment by nkruzan** [comment]
i made (untested) attempt to address the mode_mapping issues as well, please advise.

**Comment by davidbuzz** [comment]
This looks generaly great, but dont have tha ability to test right now..., will merge after someone tests it. ;-)

**Pull request merged**
