### PR TITLE
change to display that it is meters with semi-sane defaults

### PR DESCRIPTION
**Pull request by nkruzan**
change to meters with semi-sane defaults

### CODE REVIEW

**Comment by davidbuzz** [comment]
has this been tested with a write-mission-to-drone, and then read-mission-from-drone, and the result comes out still in meters..? and not accientially divided by 100 or multiplied by 100 ...?

**Comment by davidbuzz** [comment]
there's also a function in mission_control.js called 'ConvertCentimetersToMeters' that takes a (assumed) 'alt-in-cm' and converts to (assumed) alt-in-meters, and its used in three places.   need to be sure this isn't improperly dividing the wrong thing.

**Review by davidbuzz — COMMENTED** [review]
needs evidence of testing, see other comments.

**Comment by nkruzan** [comment]
> has this been tested with a write-mission-to-drone, 

wrote-to-drone then flew and it went to 50 meters as expected, instead of fly-away trying to get to 5000 meters

> and then read-mission-from-drone

read has never worked here, i didn't dig into why yet

>, and the result comes out still in meters..? and not accientially divided by 100 or multiplied by 100 ...?

is only used for display of meters next to the altitude input box as far as i can see. but yes it is displaying wrong.

**Comment by nkruzan** [comment]
> there's also a function in mission_control.js called 'ConvertCentimetersToMeters' that takes a (assumed) 'alt-in-cm' and converts to (assumed) alt-in-meters, and its used in three places. need to be sure this isn't improperly dividing the wrong thing.

those are just updating the meters displayed next to the input box from what i can see. I guess just make that `<span>` contain 'm' and remove the code that updates the text using that function.

https://mavlink.io/en/messages/common.html#MAV_CMD_NAV_WAYPOINT is expecting meters not cm so i think removing the cm would be ok ?

**Comment by nkruzan** [comment]
I made changes

**Comment by davidbuzz** [comment]
I think we're getting closer here,.

**Pull request merged**
