### PR TITLE
UDP support, for SITL and WIFI

### PR DESCRIPTION
**Pull request by nkruzan**
Seems to reliably work now with SITL. Needed to change when initial messages were sent.

Suggestions/improvements welcome as I am rusty at web dev and newish to NodeJS.

start sitl with `sim_vehicle.py  -v ArduPlane --console --map --out udp:<THE_IP_OF_YOUR_CONFIGURATOR>:14550` 
in configurator in drop down choose `Manual Selection` (at bottom) and use `udp://0.0.0.0:14550` in Port: text box

### CODE REVIEW

**Comment by davidbuzz** [comment]
I'll try to test this when I can.

**Comment by nkruzan** [comment]
this need some more work so it is reliable with real hardware...ie it works with https://github.com/ArduPilot/mavesp8266 but is a bit buggy

**Comment by davidbuzz** [comment]
there's a few bits from this PR that i'm still interested in, i can still referenrence it in its closed state... but its possible i'll cherry pick bits from this later.

**Comment by nkruzan** [comment]
Ok

**Pull request closed without merging**
