### PR TITLE
Fixup README and package versions

### PR DESCRIPTION
**Pull request by andyp1per**

### CODE REVIEW

**Comment by nkruzan** [comment]
main.html is auto generated, not sure if you intended for those changes to be included.

**Comment by nkruzan** [comment]
otherwise seems to run ok, with the minimal testing I have done.

**Comment by davidbuzz** [comment]
hey @andyp1per , thx for the PR... main.html is derived, and at the moment the one we have 'in git' is from 'npm run dev' , because most ppl are running it that way for development, if u run that, and then amend main.html, that would be consistent with how we've been doing it so-far. everything else looks good.  ( or u could drop main.html from the PR )

**Comment by andyp1per** [comment]
Ok done @davidbuzz

**Review by nkruzan — APPROVED** [review]
LGTM

**Review by davidbuzz — APPROVED** [review]

**Pull request merged**
